### ISSUE TITLE
Unpublish Empty Reviews

### ISSUE THREAD

**Issue by ghost** [tributemedia/google_reviews_testimonials#11]
Reviews that do not contain a `comment` should be unpublished.

**Comment by AntonioXIII** [comment]
Instead of unpublishing automatically, give an option to determine whether this takes place or not.

**Comment by AntonioXIII** [comment]
At a high level, this task should consist of the following:

- Add a new setting for unpublishing reviews without a `comment`. Keep in mind you may need to do more than add a setting in the settings file, work in an update hook may be necessary.
- Add an option on the Location form to toggle this setting.
- Modify import logic to unpublish empty reviews if the setting is true.

**Comment by skenley** [comment]
Import logic modified in b720aac8fb6e3acdba1935f21ae1db01bff6aa13

**Comment by AntonioXIII** [comment]
Work is done, ready for release

**Comment by AntonioXIII** [comment]
Pushed out as apart of v1.3.0.
