### ISSUE TITLE
Run Cron Button

### ISSUE THREAD

**Issue by ghost** [tributemedia/google_reviews_testimonials#13]
On the status page, a button should be added to run cron from that page. This saves the user the hassle of navigating to the cron page to run cron.

**Comment by AntonioXIII** [comment]
Resources used to figure the solution for this out:

https://codimth.com/blog/web/drupal/run-cron-programmatically-drupal-8
https://www.drupal.org/docs/drupal-apis/services-and-dependency-injection/dependency-injection-for-a-form

**Comment by AntonioXIII** [comment]
@skenley Have a look at the resources above and the commit code for this issue sometime if you're not too familiar with dependency injection in Drupal.

**Comment by AntonioXIII** [comment]
Pushed out as apart of v1.3.0.
