### ISSUE TITLE
Replace Bandaid Fix in Service Connection Form (#37)

### ISSUE THREAD

**Issue by AntonioXIII** [tributemedia/google_reviews_testimonials#41]
In #37, a bandaid fix was introduced to squash the bug. Once #40 is completed, replace the unideal fix with the usage of the new method.

https://github.com/tributemedia/google_reviews_testimonials/blob/main/src/Form/GMBServiceConnectionInfoForm.php#L97

**Comment by skenley** [comment]
Merged to dev and ready for release.

**Comment by AntonioXIII** [comment]
Pushed out as apart of v1.3.0.
